app/uk/gov/hmrc/agentclientmandate/controllers/MandateController.scala
app/uk/gov/hmrc/agentclientmandate/models/GGRelationshipDto.scala
app/uk/gov/hmrc/agentclientmandate/services/MandateCreateService.scala

ATEd-2591: Added agentCode for relationships migrated

---

app/uk/gov/hmrc/agentclientmandate/repositories/MandateRepository.scala
app/uk/gov/hmrc/agentclientmandate/services/MandateCreateService.scala
test/uk/gov/hmrc/agentclientmandate/repositories/MandateRepositorySpec.scala

also added temp code to repository for updating existing mandates

fixed createdBy.name to agentName from clientName

---

app/uk/gov/hmrc/agentclientmandate/controllers/MandateController.scala
app/uk/gov/hmrc/agentclientmandate/repositories/MandateRepository.scala
app/uk/gov/hmrc/agentclientmandate/tasks/ActivationTaskExecutor.scala
app/uk/gov/hmrc/agentclientmandate/tasks/DeActivationTaskExecutor.scala
app/uk/gov/hmrc/agentclientmandate/utils/MandateUtils.scala
test/uk/gov/hmrc/agentclientmandate/controllers/MandateControllerSpec.scala
test/uk/gov/hmrc/agentclientmandate/tasks/ActivationTaskExecutorSpec.scala
test/uk/gov/hmrc/agentclientmandate/tasks/DeActivationTaskExecutorSpec.scala
test/uk/gov/hmrc/agentclientmandate/utils/MandateUtilsSpec.scala

- when gg has allocated agent and tries to allocate again
- when gg does not have allocated agent and tries to deallocate

added handling for gg error

---

project/MicroServiceBuild.scala
project/plugins.sbt

**Dependency uplift**
* Uplifted minor dependencies for agent-client-mandate.

Uplifted dependencies for agent-client-mandate

---

project/MicroServiceBuild.scala

**Dependency uplift**
* Uplifted dependencies for agent-client-mandate, including simple-reactivemongo

DL-2119 Uplifted dependencies

---

app/uk/gov/hmrc/agentclientmandate/controllers/MandateController.scala
test/uk/gov/hmrc/agentclientmandate/controllers/MandateControllerSpec.scala

**Pipeline Unblocking**
Blocked pipeline, Jenkins won't build until coverage is met. This fixes that.

DL-2128: Added recovery block tests for test coverage minimum.

---

app/uk/gov/hmrc/agentclientmandate/tasks/ActivationTaskExecutor.scala
app/uk/gov/hmrc/agentclientmandate/tasks/DeActivationTaskExecutor.scala
it/utils/FeatureSwitchSpec.scala
project/MicroService.scala
test/uk/gov/hmrc/agentclientmandate/auth/AuthFunctionalitySpec.scala
test/uk/gov/hmrc/agentclientmandate/connectors/EmailConnectorSpec.scala
test/uk/gov/hmrc/agentclientmandate/connectors/EtmpConnectorSpec.scala
test/uk/gov/hmrc/agentclientmandate/connectors/TaxEnrolmentsConnectorSpec.scala
test/uk/gov/hmrc/agentclientmandate/controllers/MandateControllerSpec.scala
test/uk/gov/hmrc/agentclientmandate/controllers/auth/AgentDelegationForAtedControllerSpec.scala
test/uk/gov/hmrc/agentclientmandate/repositories/MandateRepositorySpec.scala
test/uk/gov/hmrc/agentclientmandate/services/AgentDetailsServiceSpec.scala
test/uk/gov/hmrc/agentclientmandate/services/MandateCreateServiceSpec.scala
test/uk/gov/hmrc/agentclientmandate/services/MandateFetchServiceSpec.scala
test/uk/gov/hmrc/agentclientmandate/services/MandateUpdateServiceSpec.scala
test/uk/gov/hmrc/agentclientmandate/services/NotificationEmailServiceSpec.scala
test/uk/gov/hmrc/agentclientmandate/services/RelationshipServiceSpec.scala
test/uk/gov/hmrc/agentclientmandate/tasks/ActivationTaskExecutorSpec.scala
test/uk/gov/hmrc/agentclientmandate/tasks/DeActivationTaskExecutorSpec.scala
test/uk/gov/hmrc/agentclientmandate/utils/MandateUtilsSpec.scala
test/uk/gov/hmrc/agentclientmandate/utils/TestAudit.scala

**Test refactor**
* Refactored out usages of FakeApplication in ACM, speeding up tests

DL-2129 Refactor out FakeApplication

---

project/MicroServiceBuild.scala
project/plugins.sbt

**Upgrade**
Upgraded sbt-build and pegged Akka-actor plugin for compatibility.

DL-2707 Upgraded sbt-build to 2.6.25

---

app/uk/gov/hmrc/agentclientmandate/connectors/TaxEnrolmentsConnector.scala

DL-2871 - Add logging statement for getGroupID

---

app/uk/gov/hmrc/agentclientmandate/connectors/TaxEnrolmentsConnector.scala

DL-2871 Added await for future

---

app/uk/gov/hmrc/agentclientmandate/auth/AuthFunctionality.scala
app/uk/gov/hmrc/agentclientmandate/binders/DelegationPathBinders.scala
app/uk/gov/hmrc/agentclientmandate/config/ScheduledJobStarter.scala
app/uk/gov/hmrc/agentclientmandate/config/ServiceBindings.scala
app/uk/gov/hmrc/agentclientmandate/connectors/RawResponseReads.scala
app/uk/gov/hmrc/agentclientmandate/connectors/TaxEnrolmentsConnector.scala
app/uk/gov/hmrc/agentclientmandate/controllers/MandateController.scala
app/uk/gov/hmrc/agentclientmandate/controllers/testOnly/PerformanceTestSupportController.scala
app/uk/gov/hmrc/agentclientmandate/repositories/MandateRepository.scala
app/uk/gov/hmrc/agentclientmandate/services/AgentDetailsService.scala
app/uk/gov/hmrc/agentclientmandate/services/MandateCreateService.scala
app/uk/gov/hmrc/agentclientmandate/services/RelationshipService.scala
app/uk/gov/hmrc/agentclientmandate/tasks/ActivationTaskExecutor.scala
app/uk/gov/hmrc/agentclientmandate/tasks/DeActivationTaskExecutor.scala
app/uk/gov/hmrc/tasks/RetryPolicy.scala
test/uk/gov/hmrc/agentclientmandate/connectors/TaxEnrolmentsConnectorSpec.scala
test/uk/gov/hmrc/agentclientmandate/tasks/DeActivationTaskExecutorSpec.scala

Dl 2871 logging

---

project/AppDependencies.scala

DL-3764: Simple-reactivemongo 7.30.0 upgrade
New feature
Simple-reactivemongo 7.30.0 upgrade

DL-3764: Simple-reactivemongo 7.30.0 upgrade

---

app/uk/gov/hmrc/agentclientmandate/controllers/MandateController.scala
app/uk/gov/hmrc/agentclientmandate/services/NotificationEmailService.scala
app/uk/gov/hmrc/agentclientmandate/services/RelationshipService.scala
app/uk/gov/hmrc/agentclientmandate/tasks/ActivationTaskExecutor.scala
app/uk/gov/hmrc/agentclientmandate/tasks/DeActivationTaskExecutor.scala
test/uk/gov/hmrc/agentclientmandate/controllers/MandateControllerSpec.scala
test/uk/gov/hmrc/agentclientmandate/services/NotificationEmailServiceSpec.scala
test/uk/gov/hmrc/agentclientmandate/tasks/ActivationTaskExecutorSpec.scala
test/uk/gov/hmrc/agentclientmandate/tasks/DeActivationTaskExecutorSpec.scala

Implement missing email notfications in the scenario where an agent cancels a mandate. UAN was not included in the email.

Dl 2630 - Implement/Fix Email notifications

---

it/helpers/LoginStub.scala

**Bug fix**
* SessionKeys is no longer supported and this PR removes it.

DL-4119 Remove SessionKeys

---

app/uk/gov/hmrc/agentclientmandate/auth/AuthFunctionality.scala
app/uk/gov/hmrc/agentclientmandate/config/ServiceBindings.scala
app/uk/gov/hmrc/agentclientmandate/controllers/AgentController.scala
app/uk/gov/hmrc/agentclientmandate/controllers/ClientController.scala
app/uk/gov/hmrc/agentclientmandate/controllers/MandateControllerNew.scala
app/uk/gov/hmrc/agentclientmandate/controllers/auth/AgentDelegationForAtedController.scala
conf/app.routes
test/uk/gov/hmrc/agentclientmandate/controllers/AgentControllerSpec.scala
test/uk/gov/hmrc/agentclientmandate/controllers/ClientControllerSpec.scala
test/uk/gov/hmrc/agentclientmandate/controllers/MandateControllerSpecNew.scala

DL-2140: Remove redundant routes - part 1
Bug fix 
Remove redundant routes - part 1

DL-2140: Remove redundant routes - part 1

---

app/uk/gov/hmrc/agentclientmandate/controllers/MandateController.scala
test/uk/gov/hmrc/agentclientmandate/controllers/MandateControllerSpec.scala
test/uk/gov/hmrc/tasks/TaskExecutorSpec.scala

DL-4478: Remove mongo as a unit test dependency

DL-4478: Remove mongo as a unit test dependency

---

app/uk/gov/hmrc/agentclientmandate/services/NotificationEmailService.scala
test/uk/gov/hmrc/agentclientmandate/services/NotificationEmailServiceSpec.scala

Fixed bug where agent rejects mandate wasn't sending an email out

Fixed bug where agent rejects mandate wasn't sending an email out

---

app/uk/gov/hmrc/agentclientmandate/config/ScheduledJobStarter.scala
app/uk/gov/hmrc/agentclientmandate/connectors/EmailConnector.scala
app/uk/gov/hmrc/agentclientmandate/connectors/EtmpConnector.scala
app/uk/gov/hmrc/agentclientmandate/connectors/TaxEnrolmentsConnector.scala
app/uk/gov/hmrc/agentclientmandate/controllers/MandateController.scala
app/uk/gov/hmrc/agentclientmandate/controllers/auth/AgentDelegationForAtedController.scala
app/uk/gov/hmrc/agentclientmandate/controllers/testOnly/PerformanceTestSupportController.scala
app/uk/gov/hmrc/agentclientmandate/repositories/MandateRepository.scala
app/uk/gov/hmrc/agentclientmandate/services/MandateCreateService.scala
app/uk/gov/hmrc/agentclientmandate/services/MandateFetchService.scala
app/uk/gov/hmrc/agentclientmandate/services/MandateUpdateService.scala
app/uk/gov/hmrc/agentclientmandate/tasks/ActivationTaskExecutor.scala
app/uk/gov/hmrc/agentclientmandate/tasks/DeActivationTaskExecutor.scala
it/controllers/MandateControllerISpec.scala
it/controllers/RelationshipServiceISpec.scala
test/uk/gov/hmrc/agentclientmandate/connectors/EmailConnectorSpec.scala
test/uk/gov/hmrc/agentclientmandate/connectors/EtmpConnectorSpec.scala
test/uk/gov/hmrc/agentclientmandate/connectors/TaxEnrolmentsConnectorSpec.scala
test/uk/gov/hmrc/agentclientmandate/controllers/AgentControllerSpec.scala
test/uk/gov/hmrc/agentclientmandate/controllers/ClientControllerSpec.scala
test/uk/gov/hmrc/agentclientmandate/controllers/MandateControllerSpec.scala
test/uk/gov/hmrc/agentclientmandate/services/AgentDetailsServiceSpec.scala
test/uk/gov/hmrc/agentclientmandate/services/MandateCreateServiceSpec.scala
test/uk/gov/hmrc/agentclientmandate/services/MandateFetchServiceSpec.scala
test/uk/gov/hmrc/agentclientmandate/services/MandateUpdateServiceSpec.scala
test/uk/gov/hmrc/agentclientmandate/tasks/ActivationTaskExecutorSpec.scala
test/uk/gov/hmrc/agentclientmandate/tasks/DeActivationTaskExecutorSpec.scala

DL-5120 - Fix for missing x-request-id and x-session-id.

---

README.md
build.sbt
project/AppDependencies.scala
project/plugins.sbt

DL-5402: Bintray update

---

app/uk/gov/hmrc/agentclientmandate/connectors/EtmpConnector.scala
app/uk/gov/hmrc/agentclientmandate/tasks/ActivationTaskExecutor.scala
app/uk/gov/hmrc/agentclientmandate/tasks/DeActivationTaskExecutor.scala
app/uk/gov/hmrc/tasks/TaskController.scala
build.sbt
conf/application.conf
project/AppDependencies.scala
test/uk/gov/hmrc/agentclientmandate/connectors/EtmpConnectorSpec.scala
test/uk/gov/hmrc/agentclientmandate/connectors/TaxEnrolmentsConnectorSpec.scala
test/uk/gov/hmrc/tasks/RetryPolicySpec.scala

DL-5279 Auth Client Upgrade

---

project/AppDependencies.scala
project/plugins.sbt

DL-8302
**Maintenance**
Upgrade hmrc-mongo dependency
Upgrade other plugin and dependencies
NOTE - not upgraded bootstrap an play as covered under different ticket

DL-8302 update hmrc-mongo plus other dependencies and plugins

---

it/controllers/RelationshipServiceISpec.scala
it/helpers/IntegrationSpec.scala
it/helpers/LoginStub.scala
project/AppDependencies.scala
project/plugins.sbt

DL-8398
**Maintenance**
Play upgrade to 2.8.16
Bootstrap upgrade to 5.25.0
Other dependency updates
Fix it tests 
ATs run for ACM

DL-8398 play and boostrap upgrade plus fix tests

---

app/uk/gov/hmrc/agentclientmandate/models/etmpAgentDetailsModels.scala
app/uk/gov/hmrc/agentclientmandate/services/AgentDetailsService.scala
conf/application.conf
project/AppDependencies.scala
project/plugins.sbt
test/uk/gov/hmrc/agentclientmandate/builders/AgentBuilder.scala

**Bug fix** (delete as appropriate)
remove unused orgType parameter from AgentDetails model

DL-12001: remove unused orgType parameter from AgentDetails model

---

app/uk/gov/hmrc/agentclientmandate/services/AgentDetailsService.scala

remove assignment to val

---

app/uk/gov/hmrc/tasks/TaskCommand.scala
app/uk/gov/hmrc/tasks/TaskRouter.scala
build.sbt
conf/application.conf

DL-12458-app-config update with pekko and few minor updates

---

app/uk/gov/hmrc/agentclientmandate/connectors/TaxEnrolmentsConnector.scala
it/test/utils/Stubs.scala

enrolment store proxy url corrected

---

conf/application.conf
project/build.properties

DL-15636 remove unused controller auth conf
